#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Utilities for geography related conversions
"""

from itaqa.geography.Italy import Province

province_enum2name = {
    Province.AL: "Alessandria",
    Province.AN: "Ancona",
    Province.AR: "Arezzo",
    Province.AP: "Ascoli Piceno",
    Province.AT: "Asti",
    Province.AV: "Avellino",
    Province.BT: "Barletta-Andria-Trani",
    Province.BL: "Belluno",
    Province.BN: "Benevento",
    Province.BG: "Bergamo",
    Province.BI: "Biella",
    Province.BS: "Brescia",
    Province.BR: "Brindisi",
    Province.CB: "Campobasso",
    Province.CE: "Caserta",
    Province.CZ: "Catanzaro",
    Province.CH: "Chieti",
    Province.CO: "Como",
    Province.CS: "Cosenza",
    Province.CR: "Cremona",
    Province.KR: "Crotone",
    Province.CN: "Cuneo",
    Province.FM: "Fermo",
    Province.FE: "Ferrara",
    Province.FG: "Foggia",
    Province.FC: "Forlì-Cesena",
    Province.FR: "Frosinone",
    Province.GR: "Grosseto",
    Province.IM: "Imperia",
    Province.IS: "Isernia",
    Province.SP: "La Spezia",
    Province.AQ: "L'Aquila",
    Province.LT: "Latina",
    Province.LE: "Lecce",
    Province.LC: "Lecco",
    Province.LI: "Livorno",
    Province.LO: "Lodi",
    Province.LU: "Lucca",
    Province.MC: "Macerata",
    Province.MN: "Mantova",
    Province.MS: "Massa-Carrara",
    Province.MT: "Matera",
    Province.MO: "Modena",
    Province.MB: "Monza e Brianza",
    Province.NO: "Novara",
    Province.NU: "Nuoro",
    Province.OR: "Oristano",
    Province.PD: "Padova",
    Province.PR: "Parma",
    Province.PV: "Pavia",
    Province.PG: "Perugia",
    Province.PU: "Pesaro e Urbino",
    Province.PE: "Pescara",
    Province.PC: "Piacenza",
    Province.PI: "Pisa",
    Province.PT: "Pistoia",
    Province.PZ: "Potenza",
    Province.PO: "Prato",
    Province.RA: "Ravenna",
    Province.RE: "Reggio Emilia",
    Province.RI: "Rieti",
    Province.RN: "Rimini",
    Province.RO: "Rovigo",
    Province.SA: "Salerno",
    Province.SS: "Sassari",
    Province.SV: "Savona",
    Province.SI: "Siena",
    Province.SO: "Sondrio",
    Province.SD: "Sud Sardegna",
    Province.TA: "Taranto",
    Province.TE: "Teramo",
    Province.TR: "Terni",
    Province.TV: "Treviso",
    Province.VA: "Varese",
    Province.VB: "Verbano-Cusio-Ossola",
    Province.VC: "Vercelli",
    Province.VR: "Verona",
    Province.VV: "Vibo Valentia",
    Province.VI: "Vicenza",
    Province.VT: "Viterbo",
    Province.BZ: "Bolzano",
    Province.TN: "Trento",
    Province.AG: "Agrigento",
    Province.CL: "Caltanissetta",
    Province.EN: "Enna",
    Province.RG: "Ragusa",
    Province.SR: "Siracusa",
    Province.TP: "Trapani",
    Province.BA: "Bari",
    Province.BO: "Bologna",
    Province.CA: "Cagliari",
    Province.CT: "Catania",
    Province.FI: "Firenze",
    Province.GE: "Genova",
    Province.ME: "Messina",
    Province.MI: "Milano",
    Province.NA: "Napoli",
    Province.PA: "Palermo",
    Province.RC: "Reggio Calabria",
    Province.RM: "Roma",
    Province.TO: "Torino",
    Province.VE: "Venezia",
    Province.UNSET: None
}

province_name2enum = {v: k for k, v in province_enum2name.items()}


def lookup_province_name(province_enum):
    """Given a Province enum, returns the province name"""
    return province_enum2name[province_enum]


def lookup_province_enum(province_name):
    """Given a province name, return the correspondent Province enum"""
    return province_name2enum[province_name]
