#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Definition of Italy regions/provinces
"""

from enum import Enum, auto


class Region(Enum):
    """Enum holding Italy's regions"""
    # yapf: disable
    ABRUZZO             = auto()
    BASILICATA          = auto()
    CALABRIA            = auto()
    CAMPANIA            = auto()
    EMILIAROMAGNA       = auto()
    FRIULIVENEZIAGIULIA = auto()
    LAZIO               = auto()
    LIGURIA             = auto()
    LOMBARDIA           = auto()
    MARCHE              = auto()
    MOLISE              = auto()
    PIEMONTE            = auto()
    PUGLIA              = auto()
    SARDEGNA            = auto()
    SICILIA             = auto()
    TOSCANA             = auto()
    TRENTINOALTOADIGE   = auto()
    UMBRIA              = auto()
    VALLEDAOSTA         = auto()
    VENETO              = auto()
    UNSET               = auto()
    # yapf: enable


class Province(Enum):
    """Enum holding Italy's provinces"""
    # TODO: Understand if needed for future queries or if not relevant
    # yapf: disable
    AL = auto()
    AN = auto()
    AR = auto()
    AP = auto()
    AT = auto()
    AV = auto()
    BT = auto()
    BL = auto()
    BN = auto()
    BG = auto()
    BI = auto()
    BS = auto()
    BR = auto()
    CB = auto()
    CE = auto()
    CZ = auto()
    CH = auto()
    CO = auto()
    CS = auto()
    CR = auto()
    KR = auto()
    CN = auto()
    FM = auto()
    FE = auto()
    FG = auto()
    FC = auto()
    FR = auto()
    GR = auto()
    IM = auto()
    IS = auto()
    SP = auto()
    AQ = auto()
    LT = auto()
    LE = auto()
    LC = auto()
    LI = auto()
    LO = auto()
    LU = auto()
    MC = auto()
    MN = auto()
    MS = auto()
    MT = auto()
    MO = auto()
    MB = auto()
    NO = auto()
    NU = auto()
    OR = auto()
    PD = auto()
    PR = auto()
    PV = auto()
    PG = auto()
    PU = auto()
    PE = auto()
    PC = auto()
    PI = auto()
    PT = auto()
    PZ = auto()
    PO = auto()
    RA = auto()
    RE = auto()
    RI = auto()
    RN = auto()
    RO = auto()
    SA = auto()
    SS = auto()
    SV = auto()
    SI = auto()
    SO = auto()
    SD = auto()
    TA = auto()
    TE = auto()
    TR = auto()
    TV = auto()
    VA = auto()
    VB = auto()
    VC = auto()
    VR = auto()
    VV = auto()
    VI = auto()
    VT = auto()
    BZ = auto()
    TN = auto()
    AG = auto()
    CL = auto()
    EN = auto()
    RG = auto()
    SR = auto()
    TP = auto()
    BA = auto()
    BO = auto()
    CA = auto()
    CT = auto()
    FI = auto()
    GE = auto()
    ME = auto()
    MI = auto()
    NA = auto()
    PA = auto()
    RC = auto()
    RM = auto()
    TO = auto()
    VE = auto()
    UNSET = auto()
    # yapf: enable
